next+header in UI
One-Language/Website pull request #34
Opened 2021-06-03 23:54 UTC by uzproblue

New react + next app initialized
Header UI from Figma created

2021-06-04 01:14 UTC, jbampton commented
You need to install `pre-commit` so that you can run some tests locally.

The `pre-commit` test is failing here.

https://github.com/One-Language/One/blob/master/CONTRIBUTING.md

2021-06-04 20:34 UTC, jbampton requested changes
MD041 Error - First line in file should be a top level header

https://github.com/One-Language/Website/pull/34/checks?check_run_id=2741855499

https://github.com/markdownlint/markdownlint/blob/master/docs/RULES.md#md041---first-line-in-file-should-be-a-top-level-header

https://github.com/One-Language/Website/blob/master/.pre-commit-config.yaml

https://pre-commit.com/

2021-06-05 05:57 UTC, jbampton commented on website/pages/api/hello.js
> +  res.status(200).json({ name: 'John Doe' })
```suggestion
  res.status(200).json({ name: 'John Doe' });
```

2021-06-05 06:01 UTC, jbampton commented on website/pages/api/hello.js
> +  res.status(200).json({ name: 'John Doe' })
```suggestion
  res.status(200).json({ name: 'John Doe' });
```

2021-06-05 06:04 UTC, BaseMax commented
John, it's ES6 code. so need to create `.jshintrc` file with:
```
{
  "esversion": 6
}
```
And I guess errors will solve!

2021-06-13 19:21 UTC, devkadirselcuk approved these changes

2021-06-13 20:39 UTC, merged